version: "3.3"
services:
  frontend:
    container_name: frontend2
    build: ./src/main/resources/frontend
    image: krystalsimmonds/sfia-three-react:v2
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./
    image: krystalsimmonds/sfia-three-spring:v2
    ports:
      - target: 9500
        published: 9500
        protocol: tcp

  nginx:
    container_name: nginx
    image: krystalsimmonds/sfia-three-nginx:v2
    ports:
      - target: 80
        published: 80
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend