apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        root /app;
        include /etc/nginx/mime.types;
        location / {
            proxy_pass http://frontend:3000;
        }
    }