- hosts: bastion
  become: true
  gather_facts: true

- hosts: jenkins
  become: true
  gather_facts: true
  # list of tasks to run on the remote machine
  tasks:
# Install Jenkins
  
  - name: 'Update'
    apt: update_cache=yes

  - name: 'Install Java and dependencies'
    apt:
      pkg:
      - openjdk-8-jre
      - wget
      - git
      - curl

  - name: 'Add Jenkins to sudoers group'
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%jenkins'
      line: '%jenkins ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'

  - name: 'Create Jenkins login'
    user:
      name: jenkins
      password: 'password'
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /home/jenkins

  - name: 'Install Jenkins apt repository key'
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
    become: yes

  - name: 'Configure repository'
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
    become: yes

  - name: 'Check Jenkins is installed'
    apt: name=jenkins update_cache=yes
    become: true

  - name: 'Change Jenkins Java options'
    lineinfile:
      dest=/etc/default/jenkins
      regexp=^JAVA_ARGS=
      line=JAVA_ARGS="Djenkins.install.runSetupWizard=false"
    become: true

  - name: 'Check Jenkins is running'
    service: name=jenkins state=started

# Install Docker

  - name: 'Install aptitude'
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: 'Install required system packages'
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common' ]

  - name: 'Add Official Docker GPG key'
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: 'Add Docker apt repository'
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: 'Update and install Docker-ce'
    apt: update_cache=yes name=docker-ce state=latest

  - name: 'Add jenkins user to docker group'
    user:
      name: "jenkins"
      group: "docker"
      append: yes

  - name: 'Install docker-compose'
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: 'install kubectl'
    command: "{{ item }}"
    with_items:
      - sudo snap install kubectl --classic

  - name: 'Install AWS'
    command: "{{ item }}"
    with_items:
      - sudo apt install awscli -y

- hosts: test
# Install Docker

  become: true
  gather_facts: true

  tasks:
    
    - name: 'Install aptitude'
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: 'Install required system packages'
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common' ]

    - name: 'Add Official Docker GPG key'
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: 'Add Docker apt repository'
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: 'Update and install Docker-ce'
      apt: update_cache=yes name=docker-ce state=latest

    - name: 'Add jenkins user to docker group'
      user:
        name: "jenkins"
        group: "docker"
        append: yes

    - name: 'Install docker-compose'
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755