- hosts: bastion
  become: true
  gather_facts: true

- hosts: jenkins
  become: true
  gather_facts: true
  # list of tasks to run on the remote machine
  tasks:
# Install Jenkins
  
  - name: 'Update'
    apt: update_cache=yes

  - name: 'Install Java and dependencies'
    apt:
      pkg:
      - openjdk-8-jre
      - wget
      - git
      - curl

  - name: 'Add Jenkins to sudoers group'
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%jenkins'
      line: '%jenkins ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'

  - name: 'Create Jenkins login'
    user:
      name: jenkins
      password: 'password'
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /home/jenkins

  - name: 'Install Jenkins apt repository key'
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
    become: yes

  - name: 'Configure repository'
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
    become: yes

  - name: 'Check Jenkins is installed'
    apt: name=jenkins update_cache=yes
    become: true

  - name: 'Change Jenkins Java options'
    lineinfile:
      dest=/etc/default/jenkins
      regexp=^JAVA_ARGS=
      line=JAVA_ARGS="Djenkins.install.runSetupWizard=false"
    become: true

  - name: 'Check Jenkins is running'
    service: name=jenkins state=started

# Install Docker

  - name: 'Install aptitude'
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: 'install Docker'
    script: docker-install.sh

  - name: 'Install Docker-Compose'
    script: docker-compose-install.sh

  - name: 'install kubectl'
    command: "{{ item }}"
    with_items:
      - sudo snap install kubectl --classic

  - name: 'Install AWS'
    command: "{{ item }}"
    with_items:
      - sudo apt install awscli -y

- hosts: test
  become: true
  gather_facts: true

  # Install Docker

  tasks:

  - name: 'Install aptitude'
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: 'install Docker'
    script: docker-install.sh

  - name: 'Install Docker-Compose'
    script: docker-compose-install.sh