- hosts: bastion
  become: true
  gather_facts: true

- hosts: Product
  # run as the root user on the remote machine
  become: true
  # list of tasks to run on the remote machine
  tasks:

  - name: 'install docker'
    script: docker.sh
  
  - name: 'install docker-compose'
    script: docker-compose.sh

  - name: 'install Jenkins'
    script: jenkins.sh
  
  - name: 'Install kubectl'
    command: "{{ item }}"
    with_items:
      - sudo snap install kubectl --classic

  - name: 'Install AWS CLI'
    command: "{{ item }}"
    with_items: 
      - sudo apt install awscli -y