- hosts: bastion
  become: true
  gather_facts: true

- hosts: Product
  become: true
  # list of tasks to run on the remote machine
  tasks:
  
  - name: 'Install kubectl'
    script: kubernetes.sh

  - name: 'Install AWS CLI'
    command: "{{ item }}"
    with_items: 
      - sudo apt install awscli -y