- hosts: bastion
  become: true
  gather_facts: true

- hosts: Product
  gather_facts: true
  # run as the root user on the remote machine
  become: true
  # list of tasks to run on the remote machine
  tasks:
  
  - name: 'Install kubectl'
    command: "{{ item }}"
    with_items:
      - sudo snap install kubectl --classic

  - name: 'Install AWS CLI'
    command: "{{ item }}"
    with_items: 
      - sudo apt install awscli -y